SuperHero/Models/ErrorViewModel.cs
using System;

namespace SuperHero.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

SuperHero/Models/SuperHeroModel.cs
using Microsoft.AspNetCore.SignalR;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SuperHero.Models
{
    public class SuperHeroModel
    {
        [Key]
        public int Id { get; set; }

        [Display(Name ="Name")]
        public string name { get; set; }
        [Display(Name = "Alter Ego")]
        public string alterEgo { get; set; }

        [Display (Name = "Primary Ability")]
        public string primaryAbility { get; set; }

        [Display (Name = "Secondary Ability")]
        public string secondaryAbility { get; set; }

        [Display (Name = "Catch Phrase")]
        public string catchPhrase { get; set; }

    }
}

SuperHero/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using SuperHero.Models;

namespace SuperHero.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SuperHero/Controllers/SuperHeroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SuperHero.Data;
using SuperHero.Data.Migrations;
using SuperHero.Models;

namespace SuperHero.Controllers
{
    public class SuperHeroController : Controller
    {

        private ApplicationDbContext _context;

        public SuperHeroController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: SuperHero
        public ActionResult Index()
        {
            var listOfHeroes = _context.SuperHeroes.ToList();
            return View(listOfHeroes);
        }

        // GET: SuperHero/Details/5
        public ActionResult Details(int id)
        {
            var hero = _context.SuperHeroes.Where(h => h.Id == id).SingleOrDefault();
            return View(hero);
        }

        // GET: SuperHero/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: SuperHero/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SuperHeroModel superHeroModel)
        {
            try
            {
                _context.SuperHeroes.Add(superHeroModel);
                _context.SaveChanges();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: SuperHero/Edit/5
        public ActionResult Edit(int id)
        {
                var heroToEdit = _context.SuperHeroes.Where(s => s.Id == id).FirstOrDefault();
                return View(heroToEdit);
        }

        // POST: SuperHero/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(SuperHeroModel superHeroModel)
        {
            var superHeroModelInDb = _context.SuperHeroes.Where(s => s.Id == superHeroModel.Id).Single();

            superHeroModelInDb.name = superHeroModel.name;
            superHeroModelInDb.primaryAbility = superHeroModel.primaryAbility;
            superHeroModelInDb.secondaryAbility = superHeroModel.secondaryAbility;
            superHeroModelInDb.catchPhrase = superHeroModel.catchPhrase;
            superHeroModelInDb.alterEgo = superHeroModel.alterEgo;

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
            
        }

        // GET: SuperHero/Delete/5
        public ActionResult Delete(int id)
        {
            var heroToDelete = _context.SuperHeroes.Where(s => s.Id == id).FirstOrDefault();
            return View(heroToDelete);
        }

        // POST: SuperHero/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, SuperHeroModel superHeroModel)
        {
            try
            {
                var superHeroToDelete = _context.SuperHeroes.Find(id);
                _context.SuperHeroes.Remove(superHeroToDelete);
                _context.SaveChanges();
                

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

SuperHero/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

    <img src="~/images/thething.jpg" alt="The Thing SuperHero" />
</div>

SuperHero/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SuperHero</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SuperHero</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SuperHero" asp-action="Create">Create Hero</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SuperHero" asp-action="">View SuperHeroes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - SuperHero - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

SuperHero/Views/SuperHero/Create.cshtml
@model SuperHero.Models.SuperHeroModel

@{
    ViewData["Title"] = "Create A SuperHero";
}

<h1>Create A SuperHero</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="name" class="control-label">Name</label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="alterEgo" class="control-label">Alter Ego</label>
                <input asp-for="alterEgo" class="form-control" />
                <span asp-validation-for="alterEgo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="primaryAbility" class="control-label">Primary Ability</label>
                <input asp-for="primaryAbility" class="form-control" />
                <span asp-validation-for="primaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="secondaryAbility" class="control-label">Secondary Ability</label>
                <input asp-for="secondaryAbility" class="form-control" />
                <span asp-validation-for="secondaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="catchPhrase" class="control-label">Catch Phrase</label>
                <input asp-for="catchPhrase" class="form-control" />
                <span asp-validation-for="catchPhrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SuperHero/Views/SuperHero/Delete.cshtml
@model SuperHero.Models.SuperHeroModel

@{
    ViewData["Title"] = "Delete A SuperHero";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.alterEgo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.alterEgo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.primaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.primaryAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.secondaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.secondaryAbility)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.catchPhrase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.catchPhrase)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

SuperHero/Views/SuperHero/Details.cshtml
@model SuperHero.Models.SuperHeroModel

@{
    ViewData["Title"] = "SuperHero Details";
}

<h1>SuperHero Details</h1>

<div>
    
    <hr />
    <dl class="row">
        <dt class="col-sm-2">

            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.alterEgo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.alterEgo)
        </dd>
        <dt class="col-sm-2">

            @Html.DisplayNameFor(model => model.primaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.primaryAbility)
        </dd>
        <dt class="col-sm-2">

            @Html.DisplayNameFor(model => model.secondaryAbility)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.secondaryAbility)
        </dd>
        <dt class="col-sm-2">

            @Html.DisplayNameFor(model => model.catchPhrase)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.catchPhrase)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

SuperHero/Views/SuperHero/Edit.cshtml
@model SuperHero.Models.SuperHeroModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>SuperHeroModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="alterEgo" class="control-label"></label>
                <input asp-for="alterEgo" class="form-control" />
                <span asp-validation-for="alterEgo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="primaryAbility" class="control-label"></label>
                <input asp-for="primaryAbility" class="form-control" />
                <span asp-validation-for="primaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="secondaryAbility" class="control-label"></label>
                <input asp-for="secondaryAbility" class="form-control" />
                <span asp-validation-for="secondaryAbility" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="catchPhrase" class="control-label"></label>
                <input asp-for="catchPhrase" class="form-control" />
                <span asp-validation-for="catchPhrase" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SuperHero/Views/SuperHero/Index.cshtml
@model IEnumerable<SuperHero.Models.SuperHeroModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.alterEgo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.primaryAbility)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.secondaryAbility)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.catchPhrase)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.alterEgo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.primaryAbility)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.secondaryAbility)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.catchPhrase)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>